# Generated by Django 4.2.4 on 2023-09-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(default='00000000', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('reamaze_url', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('ai_message', models.TextField()),
                ('human_message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
    ]
